### ISSUE TITLE
The output windows .exe can not work

### ISSUE THREAD

**Issue by prospong** [PKief/angular-cli-electron#7]
Hello,

I have followed your instructions on https://pkief.medium.com/angular-desktop-apps-a9ce9e3574e8   and I have outputed the three windows packages. But when I run them on my computer directly, the .exe file have no action when I click it. How to solve this problem?

**Comment by PKief** [comment]
Hi @prospong, sorry for the late response. The reason was that in the package script the location of the Angular app has changed. So instead of just using `dist` you have to write `dist/my-angular-app`, then it should work again. You can also clone the latest changes of this repository. I updated it to the latest Angular and Electron version and it should work fine. Please reach out if there are any additional issues.
